name = "haru-epg"
compatibility_date = "2025-08-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "haru-epg"
database_id = "9862584d-76d5-465f-a774-0d8f37ebb897"

[vars]
CACHE_TTL = "3600"

[observability]
enabled = true